###
PUT http://apiadvisor.climatempo.com.br/api-manager/user-token/:token/locales HTTP/1.1
Content-Type: application/json

{
  "localeId": [6535, 6879]
}

# {"error":true,"detail":"Your plan allows 1 cities"}
# {"error":true,"detail":"Your free plan only allows to update cities after 24 hours from the last update (2022-04-15 20:52:54 America/Sao_Paulo -03:00)"}

###



###
GET http://ip-api.com/json/?fields=status,message,country,countryCode,region,regionName,city,zip,lat,lon,timezone,isp,org,as,query HTTP/1.1

###
GET http://localhost:8083/local-weather/city/6879 HTTP/1.1

###
POST http://localhost:8083/users HTTP/1.1
Content-Type: application/json

{
  "name": "felip",
  "email": "felipe@email.com",
  "password": "123456"
}

###
GET http://localhost:8083/users HTTP/1.1

###
GET http://localhost:8083/users/2 HTTP/1.1

###
PUT http://localhost:8083/users/2 HTTP/1.1
Content-Type: application/json

{
  "name": "Felipe",
  "email": "felipe@email.com",
  "password": "123123",
  "birth_date": "1989-01-05"
}

###
DELETE http://localhost:8083/users/2 HTTP/1.1

###
PUT http://localhost:8083/users/1 HTTP/1.1
Content-Type: application/json

{
  "name": "Dalmo",
  "email": "dalmo@email.com",
  "password": "321312",
  "birth_date": "1989-01-05"
}